"""add price series and finance

Revision ID: 4abff0144055
Revises: c382bc3bf04e
Create Date: 2026-07-14 05:22:33.003699
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4abff0144055'
down_revision: str | None = 'c382bc3bf04e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_code', sa.String(length=64), nullable=False),
    sa.Column('observed_on', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_code', 'observed_on', name='uq_series_date')
    )
    op.create_index(op.f('ix_price_points_series_code'), 'price_points', ['series_code'], unique=False)
    op.create_table('price_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_series')
    op.drop_index(op.f('ix_price_points_series_code'), table_name='price_points')
    op.drop_table('price_points')
    # ### end Alembic commands ###
