"""add device_cards

Revision ID: c382bc3bf04e
Revises: b916b7b8efce
Create Date: 2026-07-13 20:16:05.433078
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c382bc3bf04e'
down_revision: str | None = 'b916b7b8efce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('stage_ratio_min', sa.Float(), nullable=False),
    sa.Column('stage_ratio_max', sa.Float(), nullable=False),
    sa.Column('stage_ratio_optimal', sa.Float(), nullable=False),
    sa.Column('isentropic_efficiency_nominal', sa.Float(), nullable=False),
    sa.Column('ratio_derate', sa.Float(), nullable=False),
    sa.Column('mass_flow_min_kg_s', sa.Float(), nullable=False),
    sa.Column('mass_flow_max_kg_s', sa.Float(), nullable=False),
    sa.Column('max_discharge_temperature_k', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_cards')
    # ### end Alembic commands ###
