"""add macro scenarios

Revision ID: f410e13a592e
Revises: 4abff0144055
Create Date: 2026-07-14 06:41:26.752541
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f410e13a592e'
down_revision: str | None = '4abff0144055'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_scenario_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_code', sa.String(length=64), nullable=False),
    sa.Column('commodity_code', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_code', 'commodity_code', 'year', name='uq_macro_point')
    )
    op.create_index(op.f('ix_macro_scenario_points_scenario_code'), 'macro_scenario_points', ['scenario_code'], unique=False)
    op.create_table('macro_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('vintage', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_scenarios')
    op.drop_index(op.f('ix_macro_scenario_points_scenario_code'), table_name='macro_scenario_points')
    op.drop_table('macro_scenario_points')
    # ### end Alembic commands ###
